export const NEW_THEME = "NEW_THEME"

export const GET_ARTICLES_REQUEST_SENT = "GET_POSTS_REQUEST_SENT";
export const GET_ARTICLES_SUCCESS ="GET_POSTS_SUCCESS";
export const GET_ARTICLES_FAILURE = "GET_POSTS_FAILURE";

export const SEARCH_ARTICLES_REQUEST = "SEARCH_ARTICLES_REQUEST";
export const SEARCH_ARTICLES_SUCCESS = "SEARCH_ARTICLES_SUCCESS";
export const SEARCH_ARTICLES_FAILURE = "SEARCH_ARTICLES_FAILURE";

export const GET_ARTICLES_HOME_REQUEST = "GET_ARTICLES_HOME_REQUEST";
export const GET_ARTICLES_HOME_SUCCESS = "GET_ARTICLES_HOME_SUCCESS";
export const GET_ARTICLES_HOME_FAILURE = "GET_ARTICLES_HOME_FAILURE";